name: pomangam_client
description: 포만감 고객용 어플리케이션

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  provider: ^4.0.1

  fluro: ^1.5.1

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0

  dio: ^3.0.8

  shared_preferences: ^0.5.6

  device_info: ^0.4.1+4

  injector: ^1.0.8

  carousel_slider: ^1.4.1

  modal_progress_hud: ^0.1.3

  transparent_image: ^1.0.0

  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.1

  build_runner: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/