name: pomangam_client
description: 포만감 고객용 어플리케이션

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  provider: ^4.0.1

  fluro: ^1.5.1

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0

  dio: ^3.0.8

  shared_preferences: ^0.5.3+5

  injector: ^1.0.8

  carousel_slider: ^1.4.1

  modal_progress_hud: ^0.1.3

  transparent_image: ^1.0.0

  flutter_html: ^0.11.1

  json_annotation: ^3.0.1

  pin_code_fields: ^2.3.0+3

  sms: ^0.2.4

  sqflite: any

  path: any

  time: ^1.2.0

  flutter_calendar_carousel: ^1.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.1

  build_runner: ^1.0.0

  json_serializable: ^3.2.5


flutter:

  uses-material-design: true

  assets:
    - assets/